// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using TaskManagement.Server.Data;

#nullable disable


namespace TaskManagement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");


            modelBuilder.Entity("TaskManagement.Server.Api.Models.TaskItem", b =>
            {
                b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

                b.Property<int>("UserId")
                 .ValueGeneratedOnAdd()
                 .HasColumnType("INTEGER");


                b.Property<DateTime>("CreatedAtDate")
                .HasColumnType("TEXT");


                b.Property<string>("Description")
                .HasColumnType("TEXT");

                b.Property<string>("UserName")
                 .HasColumnType("TEXT");


                b.Property<DateTime?>("DueDate")
                .HasColumnType("TEXT");


                b.Property<bool>("IsCompleted")
                .HasColumnType("INTEGER");


                b.Property<string>("Title")
                .IsRequired()
                .HasColumnType("TEXT");


                b.Property<DateTime>("UpdatedAtDate")
                .HasColumnType("TEXT");


                b.HasKey("Id");


                b.HasIndex("IsCompleted");


                b.ToTable("Tasks");
            });

            modelBuilder.Entity("TaskManagement.Server.Api.Models.User", b =>
            {
                b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

                b.Property<string>("Name")
                .HasColumnType("TEXT");


                b.Property<DateTime?>("Email")
                .HasColumnType("TEXT");


                b.Property<bool>("IsActive")
                .HasColumnType("INTEGER");


                b.Property<DateTime>("CreatedAtDate")
                .HasColumnType("TEXT");

                b.HasKey("Id");


                b.HasIndex("IsActive");


                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}